apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $namespace-svc-ingress
  namespace: $namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "proxy-buffers: 16 8k";
      more_set_headers "proxy-max-temp-file-size: 0";
      more_set_headers "proxy-pass-headers: header-a,header-b";
spec:
  rules:
  - host: {{INGRESS}}
    http:
      paths:
      - path: /demo-service/v1/
        backend:
          serviceName: demoservice-v1
          servicePort: 80