apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $namespace-svc-ingress
  namespace: $namespace
spec:
  rules:
  - host: {{INGRESS}}
    http:
      paths:
      - path: /demo-service/v1/
        backend:
          serviceName: demoservice-v1
          servicePort: 80