apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
  labels:
    name: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: http
  selector:
    app: nginx-ingress
